apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: docker.io/nginx:latest
        imagePullPolicy: IfNotPresent
        command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        volumeMounts:
        - name: html
          mountPath: /var/www/html/
        - name: conf
          mountPath: /etc/nginx/
        - name: log
          mountPath: /var/log/nginx/
        env:
        - name: NFS_ADDRESS # NFS地址
          value: 192.168.20.236
      volumes:
      - name: html
        nfs:
          path: /k8s/src/
          server: 192.168.20.236
      - name: conf
        nfs:
          path: /k8s/nginx/
          server: 192.168.20.236
      - name: log
        nfs:
          path: /k8s/nginx/log/
          server: 192.168.20.236

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector: 
    name: nginx
  ports:
  - port: 80 
    name: http 
    targetPort: 80 
    protocol: TCP 
  - port: 443 
    name: https 
    targetPort: 443 
    protocol: TCP 