apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: default
  annotations: 
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: www.test.com
    http:
      paths:
      - backend:
          serviceName: nginx-svc
          servicePort: 80